---
#* ESP12F sensor board script name reflecting configuration esp12f_MMmm_SSss__PP.yaml
#* Please read README.md for details
#! pin 9 do not work (it hangs ESP)- reserved for flashing;
#! pin 10 - use with caution, read https://www.letscontrolit.com/forum/viewtopic.php?t=1462
###
# Pawelo 20221127, 1.0.0, created based on esp12f_THL_SB.yml
# Pawelo 20221127, 1.1.2, renamed script to reflect sensors/switches and measures/manipulators
# Pawelo 20221127, 1.1.3, added $devices variable to nam configutation deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file
# Pawelo 20221203, 1.1.5, added Restart button on web

#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp12f_MMmm_SSss__PP.yaml --device 192.168.x.x
# heare are default values if those are not given via command line
substitutions:
#  devices: "Temperature, Humidity via SHTx30, Illuminance via BH1750,  and Doulbe Light Switch via AVT5713"
  devices: "DEV board: Temperature and Humidity via SHTx30, Illuminance via BH1750"
  project_name: "pgolawsk.esp_home"
  version: "1.1.5"

  devicename: espXX
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

# Include basics of a board
<<: !include includes/board_esp12f.yaml
# Include/Override mqtt with/without RTTTL support if needed
#<<: !include includes/mqtt.yaml
<<: !include includes/mqtt_with_rtttl.yaml

# mqtt:
#   id: mqtt_client
#   broker: !secret mqtt_ip
#   port: !secret mqtt_port
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   client_id: $devicename
#   discovery: false
#   discovery_retain: false
#   #discovery_unique_id_generator: mac
#   #discovery_object_id_generator: device_name
#   birth_message:
#   will_message:
#   shutdown_message:
#   on_message:
#     - !include { file: includes/mqtt_on_message/rtttl_play_it.yaml, vars: { topic_prefix: "$devicename", led_cycles: 1 } }
#     - !include { file: includes/mqtt_on_message/rtttl_play_it.yaml, vars: { topic_prefix: "$mqtt_location/$mqtt_room", led_cycles: 3 } }


# Include interfaces needed
<<: !include { file: interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO4", scl: "GPIO5" } }
# <<: !include { file: interfaces/dallas.yaml, vars: { gpio: "GPIO10" } }
<<: !include { file: interfaces/rtttl.yaml, vars: { ix: "" } }
# <<: !include { file: interfaces/debug.yaml, vars: { update_interval: "15s" } }
# <<: !include { file: interfaces/uart_ld2410.yaml, vars: { ix: "ld", tx_pin: "TX", rx_pin: "RX", max_distance: "4.5m" } }

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml
#  - !include sensors/text_firmware.yaml
  # - !include sensors/text_debug.yaml
  - !include sensors/text_sun_sunrise.yaml
  - !include sensors/text_sun_sunset.yaml

# binary_sensor:
#   # Double light Switch on AVT5713
#   - !include { file: sensors/binary_switch.yaml, vars: { ix: "A", gpio: "GPIO13" } }
#   - !include { file: sensors/binary_switch.yaml, vars: { ix: "B", gpio: "GPIO14" } }

#   # Doorbell at the gate
#   - !include { file: sensors/binary_doorbell.yaml, vars: { ix: "", doorbell_name: "gate", gpio: "GPIO13", delay_on: '2s' } }

#   # Distance sensor
#   - !include { file: sensors/binary_presence_ld2410.yaml, vars: { ix: "" } }

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml
  # - !include sensors/debug.yaml
  - !include sensors/sun_elevation.yaml
  - !include sensors/sun_azimuth.yaml

  # # Temperature Dallas sensor
  #  - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dtest", address: "0xc00000000c511a28" } }

  # Temperature and Humidity sensor
  - !include { file: sensors/temp_hum_SHT3x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x44" } }
  # # Temperature, Humidity and Pressure seensor
  # - !include { file: sensors/temp_hum_press_BME280.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x76" } }
  # # Temperature, Humidity, Pressure and Gas Resistance seensor
  # - !include { file: sensors/temp_hum_press_gas_BME680.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x77" } }

  # # CO2, Temperature and Humidity sensor
  # - !include { file: sensors/temp_hum_co2_SCD40.yaml, vars: { ix: "2", bus_id: "bus_a", address: "0x62" } }

  # Illuminance sensor
  - !include { file: sensors/lux_BH1750.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x23" } }
  # - !include { file: sensors/lux_color_TCS3472.yaml, vars: { ix: "2", bus_id: "bus_a", address: "0x29" } }

  # # TVOC and eCO2 sensor
  # - !include { file: sensors/tvoc_eco2_SGP30.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x58" } }

  # Water ussage YF-B10 sensor
  # - !include { file: sensors/water_YF-B10.yaml, vars: { ix: "", gpio: "GPIO12" } }
  # - !include { file: sensors/water_usage_YF-B10.yaml, vars: { ix: "" } }

  # Distance sensor
  # - !include { file: sensors/distance_ld2410.yaml, vars: { ix: "" } }

output:
  # Status LED
  - !include { file: outputs/status_led.yaml, vars: { ix: "", gpio: "GPIO10" } }

  # # Measurement LED
  # - !include { file: outputs/measurement_led.yaml, vars: { ix: "", gpio: "GPIO12" } }

  # RTTTL Buzzer (passive_buzzer)
  - !include { file: outputs/passive_buzzer.yaml, vars: { ix: "", gpio: "GPIO16" } }

  # # Double relay on AVT5713
  # - !include { file: outputs/relay.yaml, vars: { ix: "A", gpio: "GPIO5", inverted: false } }
  # - !include { file: outputs/relay.yaml, vars: { ix: "B", gpio: "GPIO12", inverted: false } }

light:
  # Status LED
  - !include { file: lights/status_led.yaml, vars: { ix: "", off_delay: "5s" } }

  # # Measurement LED
  # - !include { file: lights/measurement_led.yaml, vars: { ix: "", off_delay: "5s" } }

  # # Double relay on AVT5713
  # - !include { file: lights/light_on_relay.yaml, vars: { ix: "A" } }
  # - !include { file: lights/light_on_relay.yaml, vars: { ix: "B" } }

switch:
  # Restart button
  - !include { file: switches/platform_restart.yaml }

  # Status LED cycle
  - !include { file: switches/led_cycle.yaml, vars: { ID: "status_led", cycles: 3, on_delay: "1s" , off_delay: "500ms" } }

  # RTTTL Play (passive_buzzer)
  - !include { file: switches/rtttl_play.yaml, vars: { ix: "" } }

  # # Buzzer (active)
  # - !include { file: switches/active_buzzer.yaml, vars: { ix: "", gpio: "GPIO5", off_delay: "1100ms" } }

  # Gate switch
  - !include { file: switches/gate.yaml, vars: { ix: "", gpio: "GPIO12", off_delay: "5s", room: "Entry" } }

  # Double light Switch on AVT5713
#<<: !include switches/2lights_AVT5713.yaml
