---
# ESP12F sensor board script name reflecting configuration esp12f_MMmm_SSss__PP.yaml
#
#_ Measures used (MM)
#* T - Temperature
#* H - Humidity
# P - Pressure
# G - gas
#* I - Illuminance
#* C - CO2
# D - eCO2
# V - TVOC
# W - Water Meter
#
#_ Manipulators used (mm)
# 1r - Single Switch/Relay
#* 2l - Double Ligiht Switch
# b - Buzzer
# d - Diode
#
#_ Sensors used (SS)
#* S - SHTx30 - Temperature and Humidity
#* B - BH1750 - Illuminance
# T - TCS3472 - Illuminance and Color(s)
# P - BME280 - Temperature, Humidity, Pressure
# G - BME680 - Temperature, Humidity, Pressure, Gas
#* C - SCD40 - CO2, Temperature, Humidity
# D - SGP30 - TVOC (Total Volatile Organic Compounds), eCO2 (Equivalent Carbon Dioxide)
# Y - YF-B10 G1 - Water Pulse sensor
#
#_ Switches used (ss)
#* a - AVT5713 - Double Light Switch Board
# b - 9032A - Active Buzzer 9mm diameteer x 3.2mm height
#
#_ Purpose used (PP)
# F - Fan
#
###
# Pawelo 20221127, 1.0.0, created based on esp12f_THL_SB.yml
# Pawelo 20221127, 1.1.2, renamed script to reflect sensors/switches and measures/manipulators
# Pawelo 20221127, 1.1.3, added $devices variable to nam configutation deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file
# Pawelo 20221203, 1.1.5, added Restart button on web

#! run with this command to override sunstitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp12f_MMmm_SSss__PP.yaml --device 192.168.x.x
# heare are default values if those are not given via command line
substitutions:
  devices: "Temperature and Humidity via SHTx30, Illuminance via BH1750 and Doulbe Light Switch via AVT5713"
  project_name: "pgolawsk.esp_home"
  version: "1.1.5"

  devicename: espXX
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

<<: !include includes/board_esp12f.yaml
<<: !include includes/i2c_4_10.yaml
#<<: !include includes/dallas_2.yaml

# reinclude MQTT as a bug in ESPHOME, see: https://github.com/esphome/issues/issues/2180, https://github.com/esphome/issues/issues/1487
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
#  username: $devicename
  username: !secret mqtt_user
  password: !secret mqtt_password
  client_id: $devicename
# id: $devicename

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

  # # Temperature Dallas sensor
  # - !include sensors/temp_DS18B20.yaml

  # Temperature and Humidity sensor
  - !include sensors/temp_hum_SHT3x.yaml
  # # Temperature, Humidity and Pressure seensor
  # - !include sensors/temp_hum_press_BME280.yaml
  # # Temperature, Humidity, Pressure and Gas Resistance seensor
  # - !include sensors/temp_hum_press_gas_BME680.yaml

  # CO2, Temperature and Humidity sensor
  - !include sensors/temp_hum_co2_scd40.yaml

  # Illuminance sensor
  - !include sensors/lux_BH1750.yaml
#  - !include sensors/lux_color_TCS3472.yaml

  # # TVOC and eCO2 sensor
  # - !include sensors/tvoc_eco2_SGP30.yaml

switch:
  # Restart button
  - <<: !include switches/platform_restart.yaml

# Double light Switch on AVT5713
#<<: !include switches/2lights_AVT5713.yaml

###################
#* Further tests

# Buzzer
#<<: !include switches/active_buzzer_as_light_9032A.yaml

# Status LED
<<: !include switches/status_led_as_light_GPIO16.yaml



