---
#* ESP12F sensor board script name reflecting configuration esp12f_MMmm_SSss__PP.yaml
#* Please read README.md for details
#! pin 9 do not work (it hangs ESP)- reserved for flashing;
#! pin 10 - use with caution, read https://www.letscontrolit.com/forum/viewtopic.php?t=1462
###
# Pawelo 20221112, 1.0.0, created based on https://github.com/nygma2004/esphome
# Pawelo 20221114, 1.0.1, improved by adding secondary MQTT topic to each sensor (idea from https://community.home-assistant.io/t/publish-mqtt/324939)
# Pawelo 20221114, 1.0.3, added Material Design Icons for sensors, based on https://pictogrammers.github.io/@mdi/font/2.0.46/
# Pawelo 20221114, 1.0.4, added prometheus setup, disabled OTA via web based on https://esphome.io/components/prometheus.html
# Pawelo 20221115, 1.0.5, switched wifi to not internal sensor to make it visible in prometheus
# Pawelo 20221119, 1.0.6. added updates as parameter
# Pawelo 20221119, 1.1.0. moved to framework with !include statements
# Pawelo 20221119, 1.1.1. added esp version and wifi info text sensors to publish on web
# Pawelo 20221127, 1.1.2, renamed script to reflect sensors/switches and measures/manipulators
# Pawelo 20221127, 1.1.3, added $devices variable to name configuration deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file
# Pawelo 20221203, 1.1.5, added Restart button on web
# Pawelo 20230906, 1.1.5, switched Dallas to Dallasng custom component
# Pawelo 20230923, 1.1.5, added HA Connected binary sensor
# Pawelo, 20240902, refactoring: "status_led" renamed to "led"
# Pawelo, 20250103, added entity_category to LED

#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp12f_SSss_MMmm__PP.yaml --device 192.168.x.x
# here are default values if those are not given via command line
substitutions:
  devices: "Temperatures via DS18B20, Temperature and Humidity via SHTx30"
  project_name: "pgolawsk.esp_home"
  version: "20250103"

  devicename: esp12f-xx
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

  # default variable values for !include statements
  accuracy_decimals: "2"

# Include basics of a board
<<: !include includes/board_esp12f.yaml
# Include/Override mqtt with/without RTTTL support if needed
#<<: !include includes/mqtt.yaml
<<: !include includes/mqtt_with_rtttl.yaml

# Include interfaces needed
<<: !include { file: interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO4", scl: "GPIO5" } }
# <<: !include { file: interfaces/dallas.yaml, vars: { gpio: "GPIO14" } }
# Fix for "scratch pad checksum invalid" on dallas - using dallasng
<<: !include { file: interfaces/dallasng.yaml, vars: { gpio: "GPIO14" } }
<<: !include { file: interfaces/rtttl.yaml, vars: { ix: "" } }

# Fix for "scratch pad checksum invalid" on dallas
# external_components:
#   - source: github://ssieb/esphome@dallas
#     components: [ dallas ]
#     refresh: $updates

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml

binary_sensor:
  # HA Connected
  - !include sensors/binary_ha_connected.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

  # Temperature Dallas sensor
  # - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dwall", address: "0xc00000000c511a28" } } # 1m cable
  # - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dboiler", address: "0xba0000000ab27528" } } # 1m cable
  - !include { file: sensors/temp_DS18B20_on_dallasng.yaml, vars: { ix: "Dwall", address: "0xc00000000c511a28" } } # 1m cable
  - !include { file: sensors/temp_DS18B20_on_dallasng.yaml, vars: { ix: "Dboiler", address: "0xba0000000ab27528" } } # 1m cable
#  - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dlong", address: "0x0b0417c42dceff28" } } # 2m cable

  # Temperature and Humidity sensor
  - !include { file: sensors/temp_hum_SHT3x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x44" } }

  # Temperature Dallas sensor
  # - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dshort", address: "0xc00000000c511a28" } } # 1m cable
  # - !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Dlong", address: "0x0b0417c42dceff28" } } # 2m cable

output:
  #! needed for RTTTL but its not connected to this device
  # LED
  - !include { file: outputs/led.yaml, vars: { ix: "", gpio: "GPIO10", inverted: false } }

  # RTTTL Buzzer (passive_buzzer)
  - !include { file: outputs/passive_buzzer.yaml, vars: { ix: "", gpio: "GPIO16" } }

light:
  #! needed for RTTTL but its not connected to this device
  # LED
  - !include { file: lights/led.yaml, vars: { ix: "", platform: "binary", off_delay: "5s", entity_category: "" } }

switch:
  # # Restart button
  # - !include switches/platform_restart.yaml

  # RTTTL Play (passive_buzzer)
  - !include { file: switches/rtttl_play.yaml, vars: { ix: "" } }

button:
  # Restart button
  - !include { file: buttons/restart_button.yaml }