---
#* ESP12F sensor board script name reflecting configuration esp12f_MMmm_SSss__PP.yaml
#* Please read README.md for details
#! pin 9 do not work (it hangs ESP)- reserved for flashing;
#! pin 10 - use with caution, read https://www.letscontrolit.com/forum/viewtopic.php?t=1462
###
# Pawelo 20230103, 1.1.5, created based on THI_SB.yaml
# Pawelo 20230923, 1.1.5, added HA Connected binary sensor
# Pawelo 20240628, 1.1.5, moved filters offset adjustments for SCD40 to variables

#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp12f_MMmm_SSss__PP.yaml --device 192.168.x.x
# heare are default values if those are not given via command line
substitutions:
  devices: "Temperature and Humidity and CO2 via SHTx30 SCD40 and Illuminance via BH1750"
  project_name: "pgolawsk.esp_home"
  version: "1.1.5"

  devicename: esp12f-xx
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

  # default variable values for !include statements
  accuracy_decimals: "2"

# Include basics of a board
<<: !include includes/board_esp12f.yaml
# Include/Override mqtt with/without RTTTL support if needed
<<: !include includes/mqtt.yaml
#<<: !include includes/mqtt_with_rtttl.yaml

# Include interfaces needed
<<: !include { file: interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO4", scl: "GPIO5" } }
# <<: !include { file: interfaces/dallas.yaml, vars: { gpio: "GPIO10" } }
# <<: !include { file: interfaces/rtttl.yaml, vars: { ix: "" } }

# # reinclude MQTT as a bug in ESPHOME, see: https://github.com/esphome/issues/issues/2180, https://github.com/esphome/issues/issues/1487
# mqtt:
#   broker: !secret mqtt_ip
#   port: !secret mqtt_port
# #  username: $devicename
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   client_id: $devicename
# # id: $devicename

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml

binary_sensor:
  # HA Connected
  - !include sensors/binary_ha_connected.yaml

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

  # Temperature and Humidity sensor
  - !include { file: sensors/temp_hum_SHT3x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x44" } }
  # Illuminance sensor
  - !include { file: sensors/lux_BH1750.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x23" } }
  # Temperature, Humidity adn CO2 sensor
  - !include { file: sensors/temp_hum_co2_SCD40.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x62", temp_offset: 0.0, hum_offset: 0.0 } }

# switch:
#   # Restart button
#   - !include switches/platform_restart.yaml

button:
  # Restart button
  - !include { file: buttons/restart_button.yaml }