---
#* ESP12F sensor board script name reflecting configuration esp12f_MMmm_SSss__PP.yaml
#* Please read README.md for details
#! pin 9 do not work (it hangs ESP)- reserved for flashing;
#! pin 10 - use with caution, read https://www.letscontrolit.com/forum/viewtopic.php?t=1462
###
# Pawelo 20221117, 1.0.0, created based on edp12f_temp_hum.yml
# Pawelo 20221119, 1.0.1. added updates as parameter
# Pawelo 20221119, 1.1.0. moved to framework with !include statements
# Pawelo 20221119, 1.1.1. added esp version and wifi info text sensors to publish on web
# Pawelo 20221127, 1.1.2, renamed script to reflect sensors/switches and measures/manipulators
# Pawelo 20221127, 1.1.3, added $devices variable to name configuration deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file
# Pawelo 20221203, 1.1.5, added Restart button on web
# Pawelo 20230923, 1.1.5, added HA Connected binary sensor
# Pawelo 20240619, 1.1.5, added 2nd i2c support, secondary room/mqtt
# Pawelo 20240628, 1.1.5, moved filters offset adjustments for BME680 to variables
# Pawelo, 20240902, refactoring: "status_led" renamed to "led"
# Pawelo, 20250103, added entity_category to LED

#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp12f_MMmm_SSss__PP.yaml --device 192.168.x.x
# here are default values if those are not given via command line
substitutions:
  devices: "Temperature, Humidity, Preassure, Gas Resistance via BME680, Illuminance via BH1750 and Gate/Doorbell via GPIO"
  project_name: "pgolawsk.esp_home"
  version: "20250103"

  devicename: esp12f-xx
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room
  # (optional) secondary room/mqtt
  room2: none
  mqtt_location2: none
  mqtt_room2: none

  # default variable values for !include statements
  accuracy_decimals: "2"

# Include basics of a board
<<: !include includes/board_esp12f.yaml
# Include/Override mqtt with/without RTTTL support if needed
#<<: !include includes/mqtt.yaml
<<: !include includes/mqtt_with_rtttl.yaml

# Include interfaces needed
<<: !include { file: interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO4", scl: "GPIO5" } }
# <<: !include { file: interfaces/dallas.yaml, vars: { gpio: "GPIO10" } }
<<: !include { file: interfaces/rtttl.yaml, vars: { ix: "" } }
# <<: !include { file: interfaces/i2c_bme68x_bsec2.yaml, vars: { ix: "", address: "0x77" } }  #!not working (bricked device)


# # reinclude MQTT as a bug in ESPHOME, see: https://github.com/esphome/issues/issues/2180, https://github.com/esphome/issues/issues/1487
# mqtt:
#   broker: !secret mqtt_ip
#   port: !secret mqtt_port
# #  username: $devicename
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   client_id: $devicename
# # id: $devicename

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml
  # - !include sensors/text_air_quality_bme68x_bsec2.yaml #!not working (bricked device)
  # - !include sensors/text_IAQ_accuracy_bme68x_bsec2.yaml #!not working (bricked device)

binary_sensor:
  # HA Connected
  - !include sensors/binary_ha_connected.yaml

  # Doorbell at the gate
  - !include { file: sensors/binary_doorbell.yaml, vars: { ix: "", doorbell_name: "Doorbell", gpio: "GPIO12", delay_on: '2s', room: "${room2}", mqtt_location: "${mqtt_location2}", mqtt_room: "${mqtt_room2}" } }

sensor:
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

  # Temperature and Humidity and Preasure sensor
  - !include { file: sensors/temp_hum_press_gas_BME680.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x77", temp_offset: -2.4, hum_offset: 4.4, pressure_offset: 7.0 } }
  # - !include { file: sensors/temp_hum_press_gas_aqi_co2_voc_bme680.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x77", temp_offset: -2.4, hum_offset: 4.4, pressure_offset: 7.0 } }  #!not working (bricked device)
  # Illuminance sensor
  - !include { file: sensors/lux_BH1750.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x23" } }

output:
  # LED
  - !include { file: outputs/led.yaml, vars: { ix: "", gpio: "GPIO16", inverted: false } }

  # RTTTL Buzzer (passive_buzzer)
  - !include { file: outputs/passive_buzzer.yaml, vars: { ix: "", gpio: "GPIO13" } }

light:
  # LED
  - !include { file: lights/led.yaml, vars: { ix: "", platform: "binary", off_delay: "5s", entity_category: "" } }

switch:
  # # Restart button
  # - !include switches/platform_restart.yaml

  # LED cycle
  - !include { file: switches/led_cycle.yaml, vars: { ID: "led", cycles: 3, on_delay: "1s" , off_delay: "500ms" } }

  # RTTTL Play (passive_buzzer)
  - !include { file: switches/rtttl_play.yaml, vars: { ix: "" } }

  # Gate switch
  - !include { file: switches/gate.yaml, vars: { ix: "", gpio: "GPIO14", off_delay: "4s", room: "${room2}", mqtt_location: "${mqtt_location2}", mqtt_room: "${mqtt_room2}" } }

button:
  # Restart button
  - !include { file: buttons/restart_button.yaml }
