---
#* ESP32 sensor board script name reflecting configuration esp32_MMmm_SSss__PP.yaml
#* Please read README.md for details
###
# Pawelo 20230101, 1.1.5, created based on esp32_dev.yaml and esp12f_dev.yaml
#? ESP32-WROOM-32 minimum wiring https://www.mischianti.org/2021/05/30/esp32-wroom-32-esp32-s-flash-pinout-specs-and-ide-configuration-1/
# Pawelo 20230916, 1.1.5, added difference between 2 pulse counters as new counter
#! Pawelo 20230916, 1.1.5, (NOT DONE) fix to preserve total values between reboots, based on https://github.com/esphome/feature-requests/issues/461
# Pawelo 20230917, 1.1.5, added temp & humid via SHT30
# Pawelo 20230919, 1.1.5, added sunrise and sunset text sensors
#
#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp32_MMmm_SSss__PP.yaml --device 192.168.x.x
# heare are default values if those are not given via command line
substitutions:
  devices: "Temperature and Humidity via SHTx30, Illuminance via BH1750, Water via YF-B10 G1"
  project_name: "pgolawsk.esp_home"
  version: "1.1.5"

  devicename: esp32-xx
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

  pulses_per_liter: "476"

  # Include basics of a board
<<: !include includes/board_esp32.yaml
# Include/Override mqtt with/without RTTTL support if needed
<<: !include includes/mqtt.yaml
#<<: !include includes/mqtt_with_rtttl.yaml

# Include interfaces needed
<<: !include { file: interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO21", scl: "GPIO22" } }
#<<: !include { file: interfaces/dallas.yaml, vars: { gpio: "GPIO27" } }
# <<: !include { file: interfaces/rtttl.yaml, vars: { ix: "" } }
<<: !include { file: interfaces/dallasng.yaml, vars: { gpio: "GPIO27" } }

# # reinclude MQTT as a bug in ESPHOME, see: https://github.com/esphome/issues/issues/2180, https://github.com/esphome/issues/issues/1487
# mqtt:
#   broker: !secret mqtt_ip
#   port: !secret mqtt_port
# #  username: $devicename
#   username: !secret mqtt_user
#   password: !secret mqtt_password
#   client_id: $devicename
# # id: $devicename

text_sensor:
  - !include sensors/text_uptime.yaml
  - !include sensors/text_version.yaml
  - !include sensors/text_wifi_info.yaml
  # Sun component
  - !include { file: sensors/text_sun_sunrise.yaml, vars: { updates: "${updates}" } }
  - !include { file: sensors/text_sun_sunset.yaml, vars: { updates: "${updates}" } }

sensor:
  - !include sensors/temp_internal.yaml
  - !include sensors/uptime.yaml
  - !include sensors/wifi_signal.yaml

  # Temperature Dallas sensor
  #- !include { file: sensors/temp_DS18B20.yaml, vars: { ix: "Floor", address: "0x450417c411e3ff28" } }
  - !include { file: sensors/temp_DS18B20_on_dallasng.yaml, vars: { ix: "Floor", address: "0x450417c411e3ff28" } }

  # Temperature and Humidity sensor
  - !include { file: sensors/temp_hum_SHT3x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x44" } }
  # # Illuminance sensor
  # - !include { file: sensors/lux_BH1750.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x23" } }

  # Water ussage YF-B10 sensor
  - !include { file: sensors/water_YF-B10.yaml, vars: { ix: "_all", gpio: "GPIO16" } }
  - !include { file: sensors/water_used_YF-B10.yaml, vars: { ix: "_all" } }

  - !include { file: sensors/water_YF-B10.yaml, vars: { ix: "_garden", gpio: "GPIO17" } }
  - !include { file: sensors/water_used_YF-B10.yaml, vars: { ix: "_garden" } }

  - !include { file: sensors/water_flow_diff_YF-B10.yaml, vars: { ix: "_home",  ix_A: "_all", ix_B: "_garden", operator: "-"} }
  - !include { file: sensors/water_total_diff_YF-B10.yaml, vars: { ix: "_home",  ix_A: "_all", ix_B: "_garden", operator: "-"} }
  - !include { file: sensors/water_used_diff_YF-B10.yaml, vars: { ix: "_home",  ix_A: "_all", ix_B: "_garden", operator: "-"} }

button:
  # Restart button
  - !include { file: buttons/restart_button.yaml }

  # # Save button
  # - !include { file: buttons/save_watertotal_button.yaml }