{
 "title": "Home ESP Logs",
 "tags": [
  "MQTT",
  "ESP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ALL Logs by node",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(mqtt_node) (count_over_time({mqtt_node=~\"esp.+\"} !~ `dallasnng\\.sensor` |= `$filter` [$__range]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "ALL Logs by level",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({mqtt_node=~\"esp.+\"} !~ `dallasngg\\.sensor` |= `$filter` | decolorize | pattern `[<level>][<module>:<_>]: <_>` [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "KEY Logs by module",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(module) (count_over_time({mqtt_node=~\"esp.+\"} !~ `dallasng\\.sensor` |= `$filter` | decolorize | pattern `[<level>][<module>:<_>]: <_>` [$__range]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "KEY logs",
   "type": "logs",
   "description": "Key logs exclude Dallas sensor warnings",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{mqtt_node=~\"esp.+\"} !~ `dallasng\\.sensor` |= `$filter`",
     "legendFormat": "{{mqtt_node}}"
    }
   ]
  }
 ]
}