{
 "title": "Home Sensors",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+pressure.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Illuminance",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "lux" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+illuminance.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Temp in rooms",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+temperature.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Humidity in rooms",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+humidity.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+pressure.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temp in rooms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+temperature.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity in rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+humidity.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Illuminance in rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+illuminance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Ohter metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CO2 (Carbon Dioxide) and eCO2 (Equivalent Carbon Dioxide) in rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+co2.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TVOC (Total Volatile Organic Compounds) in rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+tvoc.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+gas_resistance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}