esphome:
  name: esp01

esp8266:
  board: esp12e

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01 Fallback Hotspot"
    password: !secret wifi_fallback_password

ota:
  safe_mode: true
  password: !secret ota_password

# Setup for HomeAssistant
#api:
#  password: !secret api_password

captive_portal:
