---
#* I2S Audio Media Player for ESP32
#! not working with esp8266
# see example: https://community.home-assistant.io/t/i2s-esp32-stereo-output-two-max98357a/573741
#
# Pawelo, 20250115, created based on https://esphome.io/components/media_player/#config-media-player
# and https://esphome.io/components/media_player/i2s_audio
# Pawelo, 20250116, added i2s_id as variable

media_player:
- platform: i2s_audio
  id: "mplayer${ix}"
  i2s_audio_id: ${i2s_id}
  i2s_dout_pin: ${dout_pin}
  name: "$room Media Player${ix}"
  icon: "mdi:play-pause"
  dac_type: external
  # mute_pin: GPIOXX
  mode: ${mode} # mono or stereo

