---
#* I2S Audio Microphone for ESP32
#! not working with esp8266
# Pawelo, 20250115, created based on https://esphome.io/components/microphone/i2s_audio
# Pawelo, 20250116, added i2s_id as variable
# Pawelo, 20250119, added i2s mic bits_per_sample and use_apll as variables

microphone:
- platform: i2s_audio
  id: "mic${ix}"
  channel: ${channel} # The channel of the microphone. One of left, right, or stereo. If stereo, the output data will be twice as big, with each right sample followed by a left sample. Defaults to right.
  # sample_rate: 16000 # I2S sample rate. Defaults to 16000.
  bits_per_sample: ${bits_per_sample} # The bit depth of the audio samples. Note that while set to 24bit or 32bit, the samples will be scaled down to 16bit before being forwarded. One of 8bit, 16bit, 24bit, or 32bit. Defaults to 32bit.
  # bits_per_channel: ${bits_per_sample} # The bit depth of the audio channels. See the datasheet of your I2S device for details. Defaults to bits_per_sample.
  use_apll: ${use_apll} # I2S using APLL as main I2S clock, enable it to get accurate clock. Defaults to false.
  # i2s_mode: primary # The I2S mode to use. One of primary (clock driven by the host) or secondary (clock driven by the attached device). Defaults to primary.
  adc_type: external
  pdm: false
  i2s_audio_id: ${i2s_id}
  i2s_din_pin: ${sd_pin} #sd
