---
#* I2S Audio Speaker for ESP32
#! not working with esp8266
# see example: https://community.home-assistant.io/t/i2s-esp32-stereo-output-two-max98357a/573741
#
# Pawelo, 20250115, created based on https://esphome.io/components/speaker/i2s_audio
# Pawelo, 20250116, added i2s_id as variable

speaker:
- platform: i2s_audio
  id: "spk${ix}"
  i2s_audio_id: ${i2s_id}
  i2s_dout_pin: ${dout_pin}
  # name: "$room Speaker${ix}"
  # icon: "mdi:speaker"
  dac_type: external
  # mute_pin: GPIOXX
  channel: ${channel} # left, right, mono or stereo

