---
#* ESP32s3 - Salon device script
#* Please read README.md for details
#* For pinout see: file://../pinouts/ESP32s3_N16R8_2xTypeC_dev_board_pinout.jpg
# NOTE: ESP32s3 - RGB led is on GPIO48
# NOTE: ESP32s3 - blue led is on GPIO44
# NOTE: ESP32s3 - green led is on GPIO43
# NOTE: PSRAM 8MB is not working? then https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto###
# NOTE: use 5V pin only if IN-OUT pads are soldered, otherwise it will deliver 2.5V only
###
# Pawelo, 20241223, created based on esp32c3_dev.yaml
# Pawelo, 20241223, added "CREATIVE" IR remote control buttons
# Pawelo, 20241231, enabled RGB LED, added pinout file reference
# Pawelo, 20250103, added RTTTL support and passive buzzer on GPIO4
# Pawelo, 20250103, added green and blue LEDs
# Pawelo, 20250103, corrected IR receiver GPIO to 6
# Pawelo, 20250104, setting device in the box - added BH1750 and pin checked working device
# Pawelo, 20250109, added option to select desired framework_type (for board include)
# Pawelo, 20250118, added RTTTL buzzer and i2s mic
# Pawelo, 20250118, commented i2s mic and added i2s sound level meter
# Pawelo, 20250119, added i2s mic bits_per_sample and use_apll as variables
# Pawelo, 20250127, set updates for Sound Level Meter to 15s
# Pawelo, 20250130, added framework_version variable
# Pawelo, 20250131, adjusted BME68x BSEC sensor variables
# Pawelo, 20250201, renamed and moved to 2_PROD folder
# Pawelo, 20250203, switch to arduino framework version "latest" to enable internal temperature sensor
# Pawelo, 20250208, added BSEC2 i2c_id selection
# Pawelo, 20250209, disabled Sound Level Meter, added MAX98357A I2S audio output with small speaker
# Pawelo, 20250221, added uptime_boot text sensor
# Pawelo, 20250304, switched to ESP-IDF (disabled BSEC2)
# Pawelo, 20250619, enabled BSEC2 for BME680, as ESPHome ESP-IDF supporting is since 2025.06 onwards
# Pawelo, 20250619, fixed IR transmitter not enabled in ESP-IDF - by forcing no PSRAM for RMT led strip component
# Pawelo, 20250619, disabled BSEC2 for BME680, as CO2 and VOC readings are definitely not true

#! run with this command to override substitutions
# esphome -s devicename espXX -s updates 1min -s room <Room name> -s mqtt_room <room> run esp32_MMmm_SSss__PP.yaml --device 192.168.x.x
# here are default values if those are not given via command line

substitutions:
  devices: "Env monitoring via BME680, Illuminance via BH1750, IR Receiver/Transmitter, RTTTL Buzzer, mic via INMP441, speaker via MAX98357A"
  project_name: "pgolawsk.esp_home"
  version: "20250619"
  esphome_min_version: 2025.6.0

  # required by ../includes/board_esp32.yaml script
  # framework_type: arduino # "arduino" or "esp-idf"
  framework_type: esp-idf # "arduino" or "esp-idf"
  framework_version: recommended # or specific version like "latest", "recommended", "4.4.4"
  # framework_version: latest # or specific version like "latest", "recommended", "4.4.4"
  board_variant: "s3" # empty for ESP32, other values to display like c3, c6, s2, s3
  board: "esp32-s3-devkitc-1" # like: esp32dev, esp32cam, esp32-c3-devkitm-1, esp32-s3-devkitc-1, lolin_s2_mini, full list here https://registry.platformio.org/platforms/platformio/espressif32/boards?version=5.3.0
  flash_size: 8MB # One of 2MB, 4MB, 8MB, 16MB or 32MB
  flash_write_interval: "5min"

  devicename: esp32-xx
  updates: "30s"
  room: Room # friendly name of room to display in HA/Web
  # this is ADDITIONAL topic and sub-topic for MQTT - it publishes under <topic>/<sub-topic>/<sensor>
  # by default it's also published under <devicename>/<id_sensor>
  mqtt_location: home
  mqtt_room: room

  # default variable values for !include statements
  accuracy_decimals: "2"

# Override some settings included below in _board_ setup
<<: !include ../includes/time_sntp_with_sun.yaml #WARN: this is to make sunrise and sunset sensor to be updated on every time sync event
<<: !include ../includes/mqtt_with_rtttl.yaml #WARN: override mqtt with RTTTL support if needed (buzzer and status led)
<<: !include { file: ../includes/logger_level.yaml, vars: { level: INFO, baud_rate: 115200 } } #WARN: override default log level to specific one
# <<: !include { file: ../includes/logger_level.yaml, vars: { level: DEBUG, baud_rate: 115200 } } #WARN: override default log level to specific one
# <<: !include { file: ../includes/logger_level.yaml, vars: { level: VERY_VERBOSE, baud_rate: 115200 } } #WARN: override default log level to specific one
# <<: !include includes/wifi_outside.yaml #WARN: override wifi to connect to outside network instead of default
# <<: !include { file: ../includes/wifi_main.yaml, vars: { } } #WARN: override wifi to connect to extended network instead of default
# <<: !include { file: ../includes/wifi_extended.yaml, vars: { } } #WARN: override wifi to connect to extended network instead of default
# <<: !include { file: ../includes/wifi_extended2.yaml, vars: { } } #WARN: override wifi to connect to extended network instead of default
# <<: !include ../includes/api_services.yaml #WARN: this is to expose services like scan_wifi (results in scan_results sensor)

# Include basics of a board
# <<: !include { file: ../includes/board_esp32.yaml, vars: { board_variant: "${board_variant}", board: "${board}", flash_size: "${flash_size}", flash_write_interval: "${flash_write_interval}" } }
# <<: !include { file: ../includes/board_esp32.yaml, vars: {} }
<<: !include { file: ../includes/board_esp32_with_psram_fix.yaml, vars: {} }
<<: !include { file: ../includes/psram.yaml, vars: { mode: "quad" } } # "quad' for 2MB, "octal" for 4-8MB PSRAM

# Include interfaces needed
<<: !include { file: ../interfaces/debug.yaml, vars: { update_interval: "5s" } }
<<: !include { file: ../interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO21", scl: "GPIO20" } }
# <<: !include { file: ../interfaces/i2c.yaml, vars: { bus_id: "bus_a", sda: "GPIO15", scl: "GPIO16" } }
# <<: !include { file: ../interfaces/dallas.yaml, vars: { gpio: "GPIO10" } }
<<: !include { file: ../interfaces/rtttl.yaml, vars: { ix: "" } }
# <<: !include { file: ../interfaces/spi.yaml, vars: { spi_id: "spi_a", clk: "GPIO6", mosi: "GPIO7", miso: "GPIO9" } }
# <<: !include { file: ../interfaces/spi_rc522.yaml, vars: { spi_id: "spi_a", cs: "GPIO5", reset: "GPIO4" } }
# <<: !include { file: ../interfaces/i2c_bme68x_bsec2.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x77", temp_offset: 0.0 } }
<<: !include { file: ../interfaces/ir_receiver.yaml, vars: { gpio: "GPIO5", dump: "nec", rmt_symbols: 64 } }
# <<: !include { file: ../interfaces/ir_receiver__arduino.yaml, vars: { gpio: "GPIO5", dump: "nec", rmt_channel: 4 } } # for ESP32c3 can be 2-3, for ESP32 can be 0-7, for ESP32s2 0-3, for ESP32s3 4-7
<<: !include { file: ../interfaces/ir_transmitter.yaml, vars: { gpio: "GPIO6", rmt_symbols: 256 } }
# <<: !include { file: ../interfaces/ir_transmitter__arduino.yaml, vars: { gpio: "GPIO6", rmt_channel: 0 } } # for ESP32c3 can be 0-1, for ESP32 can be 0-7, for ESP32s2 0-3, for ESP32s3 0-3

# # I2S Audio (!cannot be used with "I2S Sound Level Meter" below)
# i2s_audio:
#   # - <<: !include { file: ../i2s/i2s_audio.yaml, vars: { i2s_id: "i2s_all", ws_pin: "GPIO38", sck_pin: "GPIO39" } }
#   - <<: !include { file: ../i2s/i2s_audio.yaml, vars: { i2s_id: "i2s_in", ws_pin: "GPIO38", sck_pin: "GPIO39" } }
#   - <<: !include { file: ../i2s/i2s_audio.yaml, vars: { i2s_id: "i2s_out", ws_pin: "GPIO18", sck_pin: "GPIO17" } }

# <<: !include { file: ../i2s/mic.yaml, vars: { ix: "", i2s_id: "i2s_in", sd_pin: "GPIO15", channel: "left", bits_per_sample: 24bit, use_apll: true } }

# <<: !include { file: ../i2s/media_player.yaml, vars: { ix: "", i2s_id: "i2s_out", dout_pin: "GPIO16", mode: "mono" } }
# # # <<: !include { file: ../i2s/speaker.yaml, vars: { ix: "", i2s_id: "i2s_all", dout_pin: "GPIO16", channel: "mono" } }

# # # <<: !include { file: ../i2s/voice_assistant_mic_only.yaml, vars: { mic_id: "mic" } }
# # <<: !include { file: ../i2s/voice_assistant_mplayer.yaml, vars: { mic_id: "mic", mplayer_id: "mplayer" } }
# # # <<: !include { file: ../i2s/voice_assistant_speaker.yaml, vars: { mic_id: "mic", speaker_id: "spk" } }


packages:
  # I2S Media Player (!cannot be used with "I2S Sound Level Meter" below)
  mp: !include { file: ../i2s/set_i2s_media_player.yaml, vars: { dout_mode: mono, dout_pin: "GPIO16", out_ws_pin: "GPIO18", out_sck_pin: "GPIO17", din_channel: "left", din_pin: "GPIO15", in_ws_pin: "GPIO38", in_sck_pin: "GPIO39" } }

  # I2S Voice Assistant (!cannot be used with "I2S Sound Level Meter" below)
  # vass: !include { file: ../i2s/set_i2s_voice_assistant_microWW.yaml, vars: { dout_mode: mono, dout_pin: "GPIO8", out_ws_pin: "GPIO2", out_sck_pin: "GPIO1", din_channel: "left", din_pin: "GPIO4", in_ws_pin: "GPIO5", in_sck_pin: "GPIO6", rgb_light_id: rgb_led } }

  # I2S Sound Level Meter (!cannot be used with "I2S Audio" above)
  # slm: !include { file: ../i2s/set_i2s_sound_level_meter.yaml, vars: { updates: "15s", i2s_id: "i2s_db", din_pin: "GPIO15", ws_pin: "GPIO38", bck_pin: "GPIO39", channel: "left" } }

  # IR Remote control buttons added from packages
  apple_tv: !include { file: ../buttons/set_apple_tv_ir_remote.yaml, vars: { receiver: "ATV" } }
  smart_tv: !include { file: ../buttons/set_smart_tv_ir_remote.yaml, vars: { receiver: "STV" } }
  # smart_tv_x: !include { file: ../buttons/set_smart_tv_ir_remote_rest.yaml, vars: { receiver: "STVx" } }
  # nano_pc: !include { file: ../buttons/set_nano_pc_ir_remote.yaml, vars: { receiver: "NPC" } }
  # nano_pc_x: !include { file: ../buttons/set_nano_pc_ir_remote_rest.yaml, vars: { receiver: "NPCx" } }
  lg_tv: !include { file: ../buttons/set_lg_tv_ir_remote.yaml, vars: { receiver: "TV" } }
  # lg_tv_x: !include { file: ../buttons/set_lg_tv_ir_remote_rest.yaml, vars: { receiver: "TVx" } }
  yamaha_av_main: !include { file: ../buttons/set_yamaha_av_main_ir_remote.yaml, vars: { receiver: "AV" } }
  # yamaha_av_main_x: !include { file: ../buttons/set_yamaha_av_main_ir_remote_rest.yaml, vars: { receiver: "AVx" } }
  yamaha_av_zone2: !include { file: ../buttons/set_yamaha_av_zone2_ir_remote.yaml, vars: { receiver: "AV2" } }
  # yamaha_av_zone2_x: !include { file: ../buttons/set_yamaha_av_zone2_ir_remote_rest.yaml, vars: { receiver: "AV2x" } }
  yamaha_bd: !include { file: ../buttons/set_yamaha_bd_ir_remote.yaml, vars: { receiver: "BD" } }
  # yamaha_bd_x: !include { file: ../buttons/set_yamaha_bd_ir_remote_rest.yaml, vars: { receiver: "BDx" } }
  # creative: !include { file: ../buttons/set_creative_ir_remote.yaml, vars: { receiver: "CR" } }

text_sensor:
  - !include ../sensors/text_uptime.yaml
  - !include ../sensors/text_uptime_boot.yaml
  - !include ../sensors/text_version.yaml
  - !include ../sensors/text_wifi_info.yaml

  # DEBUG component
  - !include ../sensors/text_debug.yaml

  # Sun component
  - !include ../sensors/text_sun_sunrise.yaml
  - !include ../sensors/text_sun_sunset.yaml
  - !include ../sensors/text_sun_time_of_day.yaml
  - !include ../sensors/text_sun_direction.yaml

  # Air Quality sensor
  # - !include { file: ../sensors/text_air_quality.yaml }
  # - !include { file: ../sensors/text_air_quality_bme68x.yaml }
  # - !include { file: ../sensors/text_IAQ_accuracy_bme68x.yaml, vars: { platform: "bme68x_bsec2" } }

binary_sensor:
  # HA Connected
  - !include ../sensors/binary_ha_connected.yaml

sensor:
  - !include ../sensors/temp_internal.yaml #! requires "4.4.4" framework version - use latest as framework_version
  - !include ../sensors/uptime.yaml
  - !include ../sensors/uptime_boot.yaml
  - !include ../sensors/wifi_signal.yaml
  - !include ../sensors/wifi_strength.yaml

  # DEBUG component
  # - !include ../sensors/debug.yaml
  - !include ../sensors/debug_with_psram.yaml

  # Sun component
  - !include ../sensors/sun_elevation.yaml
  - !include ../sensors/sun_azimuth.yaml

  # Temperature and Humidity sensor
  # - !include { file: ../sensors/temp_hum_SHT3x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x44" } }
  # - !include { file: ../sensors/temp_hum_AHT2x.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x38" } }

  # Temperature, Humidity, Pressure and Gas Resistance sensor
  - !include { file: ../sensors/temp_hum_press_gas_BME680.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x77", temp_offset: 0.0, hum_offset: 0.0, pressure_offset: 0.0 } }
  # - !include { file: ../sensors/temp_hum_press_gas_aqi_co2_voc_bme680.yaml, vars: { platform: "bme68x_bsec2", ix: "", bus_id: "bus_a", address: "0x77", temp_offset: 0, hum_offset: 0, pressure_offset: 0 } }

  # Illuminance sensor
  - !include { file: ../sensors/lux_BH1750.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x23" } }

  # TVOC and eCO2 sensor
  # - !include { file: ../sensors/tvoc_eco2_SGP30.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x58" } }
  # - !include { file: ../sensors/tvoc_eco2_ENS160.yaml, vars: { ix: "", bus_id: "bus_a", address: "0x53" } }

button:
  # Restart, reset and shutdown buttons
  - !include { file: ../buttons/restart_button.yaml }
  - !include { file: ../buttons/safe_mode_restart_button.yaml }
  # for _dev.yaml scripts include additional buttons
  - !include { file: ../buttons/factory_reset_button.yaml }
  - !include { file: ../buttons/shutdown_button.yaml }

  # Scan Wifi button (require wifi_info text sensor to be present to display results)
  # WARN: Performing the scan will disconnect device from current WiFi
  - !include { file: ../buttons/scan_wifi_button.yaml }

  # IR Remote control buttons - include as a package
  # single remote buttons can be included here separately
  # # Apple TV Remote,MENU,Received NEC: address=0x87EE, command=0xB603 command_repeats=1
  # - !include { file: ../buttons/rc_nec_button.yaml, vars: { receiver: "AppleTV", action: "MENU", address: 0x87EE, command: 0xB603 } }
  # # some LG TV buttons - via LG
  # - !include { file: ../buttons/rc_lg_button.yaml, vars: { receiver: "LGTV", action: "POWER", data: 0x20DF10EF } }
  # - !include { file: ../buttons/rc_lg_button.yaml, vars: { receiver: "LGTV", action: "INPUT", data: 0x20DFD02F } }
  # - !include { file: ../buttons/rc_lg_button.yaml, vars: { receiver: "LGTV", action: "MUTE", data: 0x20DF906F } }
  # - !include { file: ../buttons/rc_lg_button.yaml, vars: { receiver: "LGTV", action: "BACK", data: 0x20DF14EB } }
  # # some LG TV buttons - via NEC
  # - !include { file: ../buttons/rc_nec_button.yaml, vars: { receiver: "LG_TV", action: "1", address: 0xFB04, command: 0xEE11 } }
  # - !include { file: ../buttons/rc_nec_button.yaml, vars: { receiver: "LG_TV", action: "HOME", address: 0xFB04, command: 0xBC43 } }

output:
  # LED blue (C3 supermini)
  # - !include { file: ../outputs/led.yaml, vars: { ix: "", gpio: "GPIO8", inverted: true } }

  # LED blue (S2 mini)
  # - !include { file: ../outputs/led.yaml, vars: { ix: "", gpio: "GPIO15", inverted: false } }

  # LED green (S3)
  - !include { file: ../outputs/led.yaml, vars: { ix: "", gpio: "GPIO43", inverted: true } }
  # LED blue (S3, C3 supermini plus)
  - !include { file: ../outputs/led.yaml, vars: { ix: "blue", gpio: "GPIO44", inverted: true } }
  # - !include { file: ../outputs/led.yaml, vars: { ix: "blue", gpio: "GPIO7", inverted: false } }

  # LED RGB (required only when RGB led is used as status led)
  # - !include { file: ../outputs/led_rgb.yaml, vars: { ix: "", ID: "rgb_led" } }

  # Passive/RTTTL Buzzer
  - !include { file: ../outputs/passive_buzzer_ledc.yaml, vars: { ix: "", gpio: "GPIO7" } }

light:
  # LED green (S3)
  - !include { file: ../lights/led.yaml, vars: { ix: "", platform: "binary", off_delay: "1days", entity_category: "" } }
  # LED blue (S3, C3 supermini/plus)
  - !include { file: ../lights/led.yaml, vars: { ix: "blue", platform: "status_led", off_delay: "1days", entity_category: "diagnostic" } }
  # LED RGB (S3, C3 supermini plus)
  # - !include { file: ../lights/led_rgb__arduino.yaml, vars: { ix: "", gpio: "GPIO48", entity_category: "", rmt_channel: 1 } }
  - !include { file: ../lights/led_rgb.yaml, vars: { ix: "", gpio: "GPIO48", entity_category: "", rmt_symbols: 64  } }
  # - !include { file: ../lights/led_rgb_neopixelbus.yaml, vars: { ix: "", gpio: "GPIO48", entity_category: "" } }

switch:
  # LED cycle
  - !include { file: ../switches/led_cycle.yaml, vars: { ID: "led", cycles: 3, on_delay: "1s" , off_delay: "1000ms" } }

  # Passive/RTTTL Buzzer
  - !include { file: ../switches/passive_buzzer.yaml, vars: { ix: "", off_delay: "500ms" } }
  - !include { file: ../switches/passive_buzzer_cycle.yaml, vars: { ix: "", cycles: 2, freq: "1000Hz", on_delay: "500ms", off_delay: "200ms" } }
  - !include { file: ../switches/passive_buzzer_cycle.yaml, vars: { ix: "", cycles: 3, freq: "2000Hz", on_delay: "500ms", off_delay: "200ms" } }
  - !include { file: ../switches/passive_buzzer_cycle.yaml, vars: { ix: "", cycles: 4, freq: "800Hz", on_delay: "500ms", off_delay: "200ms" } }

  # RTTTL Play (passive_buzzer)
  - !include { file: ../switches/rtttl_play.yaml, vars: { ix: "" } }
  # - !include { file: ../switches/rtttl_play.yaml, vars: { ix: "2", mqtt_location: "${mqtt_location2}", mqtt_room: "${mqtt_room2}" } }