{
 "title": "Home ESP Logs",
 "tags": [
  "MQTT",
  "ESP"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {}
   },
   { "name": "filter", "label": "LOG Filter" }
  ]
 },
 "panels": [
  {
   "title": "Devices and their versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Info for ALL nodes",
     "type": "table",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "esphome_text_sensor_value{id=~\".*_esphome_version\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Debug info for all nodes",
     "type": "table",
     "gridPos": { "h": 14, "w": 16, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "  esphome_text_sensor_value{id=~\".*_device_info\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Logs charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "By node",
   "type": "piechart",
   "description": "Logs by node",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(mqtt_node) (count_over_time({mqtt_node=~\"$node\"} |= `$filter` [$__auto]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "By level",
   "type": "piechart",
   "description": "Logs by level",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({mqtt_node=~\"$node\"} |= `$filter` | decolorize | pattern `[<level>][<module>:<_>]: <_>` [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "By module",
   "type": "piechart",
   "description": "Logs by module",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(module) (count_over_time({mqtt_node=~\"$node\"} |= `$filter` | decolorize | pattern `[<level>][<module>:<_>]: <_>` [$__range]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "type": "logs",
   "description": "Key logs exclude Dallas sensor warnings",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{mqtt_node=~\"$node\"} |= `$filter`| line_format \"[{{.mqtt_node}}]\\t{{__line__}}\"",
     "legendFormat": "{{mqtt_node}}"
    }
   ]
  }
 ]
}