{
 "title": "Home Sensors",
 "tags": [
  "prometheus",
  "ESP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "slm_esp_node",
    "label": "SLM node",
    "query": {
     "query": "label_values({id=~\".*_slm_l\\\\D+_\\\\d.+\"},friendly_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Device metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WIFI Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+signal.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Device Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+-.+temperature.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+voltage.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current conditions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+pressure.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Illuminance",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "lux" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+illuminance.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Temp in rooms",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 518 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+temperature.*\", id!~\".+color.+\", id!~\".+-.+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Humidity in rooms",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 527 },
     "fieldConfig": { "defaults": { "unit": "humidity" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+humidity.*\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Trends", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+pressure.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+temperature.*\", id!~\".+color.+\", id!~\".+-.+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+humidity.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Illuminance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+illuminance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+uv_index.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ambient and UV Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+_counts.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Ohter metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CO2 (Carbon Dioxide) and eCO2 (Equivalent Carbon Dioxide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+co2.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "TVOC (Total Volatile Organic Compounds) and Breathable VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+voc.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Water usage [10min delta]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "delta(esphome_sensor_value{id=~\".+water_total_[^_]+$\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Water usage [1h delta]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "delta(esphome_sensor_value{id=~\".+water_total_[^_]+$\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Water usage [1h delta]",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "expr": "delta(esphome_sensor_value{id=~\".+water_total_[^_]+$\"}[1h])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=~\".+gas_resistance.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Deprecated / NOT in use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 },
   "collapsed": true,
   "panels": [
    {
     "title": "Color Channels",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 447 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".+channel.+\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": " Sound Level Meter - $slm_esp_node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 455 },
     "repeat": "slm_esp_node",
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "expr": "esphome_sensor_value{id=~\".*_slm_.*l\\\\D+_\\\\d.+\", friendly_name=\"$slm_esp_node\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}