---
#* Double Light Switch on AVT5713
# Pawelo, 20221127, created as new based on https://esphome.io/cookbook/sonoff-t1-3#t2
# Pawelo, 20221127, renaming switches, adding mqtt publis topics
# Pawelo, 20221203, adding on_release action to binary_sensor, to simulate regular light switches

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "$room Switch 1"
    id: switch_1
    state_topic: $devicename/switch1
    on_press:
      then:
        - light.toggle: light_1
    on_release:
      then:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: GPIO14
      mode:
        input: true
        pullup: true
      inverted: true
    name: "$room Switch 2"
    id: switch_2
    state_topic: $devicename/switch2
    on_press:
      then:
        - light.toggle: light_2
    on_release:
      then:
        - light.toggle: light_2

output:
  - platform: gpio
    pin: GPIO5
    id: relay_1

  - platform: gpio
    pin: GPIO12
    id: relay_2

light:
  - platform: binary
    name: "$room Light 1"
    id: light_1
    state_topic: $devicename/light1
    output: relay_1
    # on_state:
    #   - mqtt.publish:
    #       topic: "$mqtt_location/$mqtt_room/light1"
    #       payload: !lambda |-
    #         return to_string(id(light_1).state);


  - platform: binary
    name: "$room Light 2"
    id: light_2
    state_topic: $devicename/light2
    output: relay_2
    # on_state:
    #   - mqtt.publish:
    #       topic: "$mqtt_location/$mqtt_room/light2"
    #       payload: !lambda |-
    #         return to_string(id(light_2).state);
