---
#* Base configuration for ESP-01s board
# Pawelo 20221222, created based on my framework and https://www.esphome-devices.com/devices/ESP-01S-1-channel-relay
# Pawelo 20230305, added time_sntp and sun by default
# Pawelo 20231020, moved sun component update on time sync only (every 5 min by default)
# Pawelo, 20241115, added area and friendly name

esphome:
  name: $devicename
  friendly_name: $room
  area: $room
  comment: $room ESP01s controller with $devices
  project:
    name: $project_name
    version: $version

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

preferences:
  flash_write_interval: 1min

<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include mqtt.yaml
<<: !include logger.yaml
<<: !include { file: web_server.yaml, vars: { ota_enabled: false } }
<<: !include time_sntp_with_sun.yaml
<<: !include sun.yaml
<<: !include prometheus.yaml

# packages:
#   network: !include mqtt.yaml