---
#* Base configuration for ESP32C3 SuperMini board (https://pl.aliexpress.com/item/1005006096717048.html)
#! in case different setup needed please include components PRIOR the board itself
# Pawelo 20231205, created as copy of board_esp32_with_sun.yaml
# Pawelo, 20241117, added regular mqtt (no RTTL support), regular time snmp (with no sun)
# Pawelo, 20241119, shortened esphome comment
# Pawelo, 20241221, set flash_write_interval to 15min

esphome:
  name: $devicename
  friendly_name: $room
  area: $room
  comment: $room ESP32c3 with $devices
#  platform: ESP8266   # OLD notation
  project:
    name: $project_name
    version: $version

esp32:
  board: esp32-c3-devkitm-1
#  restore_from_flash: true
  # framework:
  #   # type: arduino
  #   type: esp-idf

preferences:
  flash_write_interval: 15min

<<: !include wifi.yaml
# <<: !include wifi_extended.yaml
# <<: !include wifi_main.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include logger.yaml
<<: !include { file: web_server.yaml, vars: { ota_enabled: false } }
<<: !include time_sntp.yaml
<<: !include sun.yaml
<<: !include prometheus.yaml
<<: !include mqtt.yaml