
esphome:
  name: $devicename
  friendly_name: Testing ESP32S2 Dev for 1st flash
  comment: To flash it only
  # platformio_options:
    # upload_speed: 115200
    # upload_speed: 57600

esp32:
  # board: lolin_s2_mini
  board: lolin_s2_pico
  # board: esp32-s2-saola-1
  # variant: ESP32S2
  # framework:
  #   type: esp-idf
  #   version: recommended
  # framework:
  #   type: arduino
  #   version: 2.0.6
  #   platform_version: 5.3.0
wifi:
  power_save_mode: none
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    hidden: true
  fast_connect: true

  ap:
    ssid: "$devicename Recovery"
    password: !secret wifi_fallback_password

captive_portal:

web_server:
  port: 80
  include_internal: true
  ota: false
  version: 3

logger:
  #  level: NONE, ERROR, WARN, INFO, DEBUG (default), VERBOSE, VERY_VERBOSE
  level: DEBUG
  #  level: WARN
  # level: DEBUG
  #  level: VERY_VERBOSE
  # disable UART logging
  baud_rate: 115200

ota:
  platform: esphome
  # safe_mode: true
  password: !secret ota_password

safe_mode:

mqtt:
  id: mqtt_client
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password