---
#* Base configuration for ESP-32-WROOM board
#! in case different setup needed please include components PRIOR the board itself
# WARN: PSRAM 8MB is not working? then https://community.home-assistant.io/t/esp32-s3-devkitc-1-n16r8-using-psram-howto

# Pawelo 20230101, created as copy of board_esp12f.yaml
# Pawelo 20230305, added time_sntp amd sun by default
# Pawelo 20230924, increased flash_write_interval to 15min
# Pawelo, 20241115, added area and friendly name
# Pawelo, 20241119, simplified - added regular mqtt (no RTTTL support), as it can be override PRIOR this file include
# Pawelo, 20241122, removed flash_write_interval to no saves into flash
# Pawelo, 20241222, make "board" and "board variant" as variables
# Pawelo, 20241222, added flash_size as variable
#? Pawelo, 20241222, created as copy of board_esp32.yaml with additional platformio_options to enable PSRAM gor N16R8 board variant
# Pawelo, 20250103, renamed script and added flash_mode as dio
# Pawelo, 20250109, added framework_type variable recognition

esphome:
  name: $devicename
  friendly_name: $room
  area: $room
  comment: $room ESP32${board_variant} with $devices
#  platform: ESP8266   # OLD notation
  project:
    name: $project_name
    version: $version

  # FIX for PSRAM on N16Rx board variants - arduino options are not set by default in ESPHome(?)
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    board_upload.maximum_ram_size: 524288
    board_build.flash_mode: dio

esp32:
  board: ${board} # like: esp32dev, esp32cam, esp32-c3-devkitm-1, esp32-s3-devkitc-1, esp32-s2-saola-1, full list here https://registry.platformio.org/platforms/platformio/espressif32/boards?version=5.3.0
  flash_size: ${flash_size} # One of 2MB, 4MB, 8MB, 16MB or 32MB
#  restore_from_flash: true
  framework:
    type: ${framework_type} # arduino or esp-idf

preferences:
  flash_write_interval: ${flash_write_interval}

<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include logger.yaml
<<: !include { file: web_server.yaml, vars: { ota_enabled: false } }
<<: !include time_sntp.yaml
<<: !include sun.yaml
<<: !include prometheus.yaml
<<: !include mqtt.yaml
