---
#* Base configuration for ESP-12F board
# Pawelo 20221119, created as my framework based on !include statements
# Pawelo 20221127, 1.1.3, added $devices variable to name configutation deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file

esphome:
  name: $devicename
  comment: $room ESP12F controller with $devices
  platform: ESP8266
  board: esp12e
  project:
    name: $project_name
    version: $version

<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include logger.yaml
<<: !include web_server.yaml
<<: !include prometheus.yaml
<<: !include mqtt.yaml

# packages:
#   network: !include mqtt.yaml