---
#* Base configuration for ESP-32-CAM-MB board
# Pawelo 20230112, created as copy of board_esp32.yaml
# Pawelo 20230305, added time_sntp amd sun by default

esphome:
  name: $devicename
  comment: $room ESP32 Camera controller with $devices
#  platform: ESP8266   # OLD notation
  project:
    name: $project_name
    version: $version

esp32:
  board: esp32cam
#  restore_from_flash: true

preferences:
  flash_write_interval: 1min

<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include logger.yaml
<<: !include { file: web_server.yaml, vars: { ota_enabled: false } }
<<: !include time_sntp.yaml
<<: !include sun.yaml
<<: !include prometheus.yaml
#! as mqtt cannot be overwriten later in the code need to include in in each script (to facilitate "on_message" customization)
#<<: !include mqtt.yaml

# packages:
#   network: !include mqtt.yaml