---
#* Base configuration for ESP-12F board
# Pawelo 20221119, created as my framework based on !include statements
# Pawelo 20221127, 1.1.3, added $devices variable to name configutation deployed
# Pawelo 20221127, 1.1.4, moved i2c configuration to separate include file
# Pawelo 20221127, 1.1.5, added preserving values in flash

esphome:
  name: $devicename
  comment: $room ESP12F controller with $devices
#  platform: ESP8266   # OLD notation
  project:
    name: $project_name
    version: $version

esp8266:
  board: esp12e
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

<<: !include wifi.yaml
<<: !include api.yaml
<<: !include ota.yaml
<<: !include mqtt.yaml
<<: !include logger.yaml
<<: !include web_server.yaml
<<: !include prometheus.yaml

# packages:
#   network: !include mqtt.yaml